version: "2"
services:
  jenkins:
    image: jenkinsci/blueocean
    user: root
    ports:
      - "8080:8080" # web-interface
      - "8443:8443" # web-interface with ssl
      - "50000:50000" # remote Java (JIRA) API
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - ./:/home
      - /var/run/docker.sock:/var/run/docker.sock # reuse docker on the host
